### ISSUE TITLE
Error in the get_speedup function

### ISSUE THREAD

**Issue by dzamlo** [andrewpsuedonym/Dissertation-Project#1]
In the `parse.py script, there is an error in the get_speedup` function.
When i is 0, you change the value of res[0] (always to 1.0). But the you continue to use res[0] for the other lines. 

For the Copy case of the rust data, the frst two values are 0.06837 and 0.03525. With no bug the second result should be 0.06837 / 0.03525 =  1.94, but instead you get 1 / 0.03525 = 28.37.

That explain the strangely high speedup of more than the number of cores.

**Comment by andrewpsuedonym** [comment]
Wow. Shit. Thanks


On 22 May 2019 at 10:38 pm, <Loïc Damien<mailto:notifications@github.com>> wrote:


In the parse.py script, there is an error in the get_speedup function.
When i is 0, you change the value of res[0] (always to 1.0). But the you continue to use res[0] for the other lines.

For the Copy case of the rust data, the frst two values are 0.06837 and 0.03525. With no bug the second result should be 0.06837 / 0.03525 = 1.94, but instead you get 1 / 0.03525 = 28.37.

That explain the strangely high speedup of more than the number of cores.
